### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by miDeb** [davidmarne/built_redux#104]
I wanted to use `flutter_built_redux`, but when running `flutter packages get`, the following error appears:
```
Because built_redux >=7.4.5 depends on analyzer ^0.32.1 and built_redux >=0.0.3 <7.4.5 requires SDK version >=1.17.1 <2.0.0 or >=2-0-0-dev <2.0.0, built_redux >=0.0.3 requires analyzer ^0.32.1.
And because every version of flutter_test from sdk depends on analyzer 0.33.0 and flutter_built_redux >=0.6.0 depends on built_redux >=6.1.1 <8.0.0, flutter_test from sdk is incompatible with flutter_built_redux >=0.6.0.
So, because my_project_name depends on both flutter_built_redux ^0.6.0 and flutter_test any from sdk, version solving failed.
```
This is only happening with the master or dev channel of flutter, the beta channel works fine.

**Comment by jkyon** [comment]
I had the same issue, but in the beta channel (v0.10.2), and I could not fix it.
the error is:

Because built_redux 7.5.0 depends on analyzer ^0.32.1 and every version of flutter_test from sdk depends on analyzer 0.33.0, built_redux 7.5.0 is incompatible with flutter_test from sdk.
So, because my_project_name depends on both built_redux 7.5.0 and flutter_test any from sdk, version solving failed.
pub get failed (1)

**Comment by zoechi** [comment]
Try
```
dependency_overrides:
  analyzer: ^0.33.0
```

**Comment by miDeb** [comment]
Thanks!

**Comment by miDeb** [comment]
Sorry
I hadn't in mind that

**Comment by maxlapides** [comment]
Similarly, `build_runner` should be upgraded in `built_redux`

**Comment by Findulas** [comment]
With angular 5.2.0 the problem persists for the analyzer.

Wouldn't it be helpful to specify ranges instead of the carret notation depending on the compatibility statements of the used projects?

  analyzer: '>=0.33.0 <1.0.0'
  build: '>=1.0.0 <2.0.0'

**Comment by miDeb** [comment]
I guess this can't be an issue anymore, since new versions have been released. If this happens again, a new issue should be opened.
