### ISSUE TITLE
Counter example prints the final value only, not every state changes

### ISSUE THREAD

**Issue by giraldeau** [davidmarne/built_redux#47]
Using the counter example, the listen event appears out of order with respect to the program order. The call `store.stream.listen((_) => print(store.state.count));` always just print the final count, as if the call was differed after all updates. This is confirmed using the following simple example:

```
store.stream.listen((event) => print("listen: ${event.prev.count} -> ${event.next.count}"));
print("current value: ${store.state.value});
store.actions.increment(1);
print("current value: ${store.state.value});

output:
current value: 0
current value: 1
listen: 0 -> 1
```
I was expecting that the listen callback would be called from within the event dispatching, but it seems they are queued and batched. I wonder why this behaviour occurs. We might change the example to used the StoreChange argument instead of the global store to yield the expected result.

**Comment by davidmarne** [comment]
Hey, so you're example produces the expected behavior. The actions will be executed synchronously, so the stream handler for each event will not be processed until the the event dispatching the actions has completed. 

I do see why the README.md example is confusing/wrong it would probably be more accurate if it was:

```dart
store.stream.listen((change) => print(change.next));

// The only way to mutate the internal state is to dispatch an action.
store.actions.increment(1);
store.actions.increment(2);
store.actions.decrement(1);
// 1
// 3
// 2
```

because the handlers for each stream event will process after all of the actions. I'll update the README, thanks!

For more info check out https://webdev.dartlang.org/articles/performance/event-loop

**Comment by giraldeau** [comment]
Great explanation, thanks!
