### ISSUE TITLE
Best practices for server integration ?

### ISSUE THREAD

**Issue by gedw99** [davidmarne/built_redux#50]

**Comment by davidmarne** [comment]
I assume by server integration you mean communicating with a server, not running built_redux on the server? If so see:
https://github.com/davidmarne/built_redux/issues/12

Performing network request in a middleware as exemplified in the response to that issue is the idiomatic way to do it without introducing any additional dependencies. However there are also a couple of libraries to help make the task even simpler:
https://github.com/davidmarne/built_redux_thunk
https://github.com/davidmarne/built_redux_rx

Both of those have examples of performing network requests in their respective READMEs

**Comment by gedw99** [comment]
thanks David thats answers it nicely in #12 

I will have a look at some others examples using your libs to get a feel for it

**Comment by gedw99** [comment]
i use golang for server side and running on desktops and mobiles, and have to decide the best integration.
RPC; GRPC, etc etc etc ?
Is there anything that you can recommend for built_redux ?

**Comment by zoechi** [comment]
I don't see how any of this is related to redux. Communication with the server is outside of Redux and Redux isn't involved at all.

**Comment by gedw99** [comment]
true its outside the scope.

I will leave this here anyway for others:
Reflux is essentially a control plane doing East West pub sub between components. I am asking about North South pub sub in terms of integrations. DGraph and NATS are obvious ones to integrate
