### ISSUE TITLE
"flutter packages get" gets stuck

### ISSUE THREAD

**Issue by kostaa** [davidmarne/built_redux#63]
Both "flutter packages get" and "pub get "get stuck and fail to complete.

**Comment by zoechi** [comment]
looks like a dup of #56

**Comment by davidmarne** [comment]
yea, that is definitely possible if you are trying to use the latest versions of built_value and build. If that is the case, i just published a [dev branch](https://github.com/davidmarne/built_redux/tree/7.4.0-dev,) that works with the latest versions, so pub should resolve with that version.

@kostaa will you post your pubspec.yaml if that dev branch doesn't work for you?

**Comment by zoechi** [comment]
I think it should have been published as 7.5.0-dev instead.
Nothing serious, but `built_redux: ^7.4.0-dev` fetches `7.4.0` because it's newer

**Comment by kostaa** [comment]
Thanks for that all is good now.

**Comment by davidmarne** [comment]
@zoechi pub would still fetch `7.4.0` if it was made as `7.5.0-dev`. [From pub_semver:](https://pub.dartlang.org/packages/pub_semver)

>  when pub is choosing a version, it uses priority order which is different from strict comparison ordering. Any stable version is considered higher priority than any unstable version. The above versions, in priority order, are:
1.2.0-alpha
1.3.0-experimental
1.0.0
1.2.0

Essentially the only way pub will resolve to the dev tag is if you have it pinned or if it is forced to resolve to the dev tag due to dependency constraints.

**Comment by zoechi** [comment]
If xou published it as `7.5.0-dev` then yes, I only saw `7.4.0-dev`.
Perhaps I checked to early
