### ISSUE TITLE
Listen store changes on actionStream. Flutter (Channel master, v0.2.7-pre.2 )

### ISSUE THREAD

**Issue by tdesc88** [davidmarne/built_redux#64]
Hello,
I want listen store change on event named "AppActionsNames.startLoginFlow" and it changes single variable in AppState  ... bool get startedLoginFlow;
` 
store.actionStream(AppActionsNames.startLoginFlow).listen((StoreChange<AppState, AppStateBuilder, Action<Null>> change)`
When action occurs, i got an error 
Action {
  name: AppActions-startLoginFlow,
  payload: null,
}
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'StoreChange<AppState, AppStateBuilder, dynamic>' is not a subtype of type 'StoreChange<AppState, AppStateBuilder, Null>' in type cast where
Replacing `Action<Null>` to `Null` and `dynamic` doesnt help.

**Comment by tdesc** [comment]
store.actionStream(AppActionNames.increment).listen((change) {
    print('Previous: ${change.prev.count}');
    print('Next: ${change.next.count}');
    print('Action: ${change.action.name}');
});

**Comment by davidmarne** [comment]
interesting. So FWIW it should be:
`store.actionStream(AppActionsNames.startLoginFlow).listen((StoreChange<AppState, AppStateBuilder, Null> change){})`

and not

`store.actionStream(AppActionsNames.startLoginFlow).listen((StoreChange<AppState, AppStateBuilder, Action<Null>> change){})`

but 

`store.actionStream(AppActionsNames.startLoginFlow).listen((change) {})`

also should work and be able to infer the type of `change`. It sounds like you tried all of those variations though.

I have a test here which is passing without any issues on dart 1.24.3 and 2.0.0-dev.46.0:
https://github.com/davidmarne/built_redux/blob/master/test/unit/store_test.dart#L112

How is the `startLoginFlow` ActionDispatcher defined? Like so?
`ActionDispatcher<Null> get startLoginFlow`?

**Comment by davidmarne** [comment]
If you'ld like to check, I would be curious if that tests passes on your machine if you clone down the repo just run:

`pub get`
`ddev test`

**Comment by tdesc** [comment]
SLVR: Solving dependencies:
    | - test ^0.12.0 from hosted (test)
    | - source_gen ^0.7.0 from hosted (source_gen)
    | - built_collection >=1.0.0 <4.0.0 from hosted (built_collection)
    | - built_value >=4.1.0 <6.0.0 from hosted (built_value)
    | - build >=0.10.0 <0.12.0 from hosted (build)
    | - analyzer >=0.29.0 <0.31.0 from hosted (analyzer)

**Comment by davidmarne** [comment]
ahh i see, so couple things here:
1. your get is probably failing because because another dependency that depends on the latest build runner. The latest build runner only works with dart 2, so I made a dev branch [here](https://github.com/davidmarne/built_redux/tree/7.4.0-dev), which works with the latest build runner.

2. I think i actually see what is causing the original issue. It is the way [this](https://github.com/davidmarne/built_redux/blob/7.4.0-dev/lib/src/store.dart#L126) cast is written. It works in dart 1, but with dart 2's stricter type system that cast is not allowed. 

I will get a fix in, thanks for finding this and bringing it up

**Comment by tdesc** [comment]
Thanks alot. Your packages are great and very useful =)
