### ISSUE TITLE
Thoughts on adding .g.dart to .gitignore

### ISSUE THREAD

**Issue by ga6559** [davidmarne/built_redux#68]
First, I want to congratulate you guys on the awesome work on this project.

I saw some example projects and they all have .g.dart files committed. Any reason for that? It's safe for me to add them to .gitignore? 

Thanks.

**Comment by zoechi** [comment]
I prefer to see when calling build causes changes in the generated code.
I also have `built_redux` and `built_value` in a sub-project.
If I'd add this sub-project as git-dependency it wouldn't work because without the generated files the code is just not invalid and I can't generate the files of a dependency in the application project.

If you don't care about any of this not committing these files should be fine.
